version: '3.8'

services:
  # Frontend React
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: app_frontend
    env_file:
     - frontend/.env
    ports:
     - "5173:5173"
    depends_on:
     - backend
    volumes:
     - ./frontend:/app_frontend
     - /app/node_modules
    networks:
     - app-network

  # Backend Node.js
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: app_backend
    env_file:
     - ./backend/.env
    ports:
     - "3000:3000"
    depends_on:
     - db
    volumes:
     - ./backend:/app
     - /app/node_modules
    networks:
     - app-network

  # Bade de Datos PostgreSQL
  db:
    image: postgres:14-alpine
    container_name: app_db
    env_file:
      - ./backend/.env
    ports:
      - "5432:5432"
    volumes:
      - postgres data:/var/lib/postgresql/data
      - ./backend/prisma/migration:/docker-entrypoint-initdb.d
    networks:
      - app-network

networks:
 app-network:
  driver: bridge

volumes:
 postgres data :
  driver: local
    