
GET http://localhost:3000/usuarios/

###

DELETE http://localhost:3000/usuars/98

###
POST http://localhost:3000/usuarios/
Content-Type: application/json

{
    "nombre": "lautaro",
    "contraseña": "jasjiasja",
    "mail": "aaa",
    "descripcion": "tengo una buena pc",
    "rolPostulante": true,
    "fecha": "2004-10-07T00:00:00",
    "fotoperfil": "string",
}